//! Renders the delimited router block and writes it into a `CLAUDE.md` file
//! without disturbing anything outside the markers.
//!
//! The block is a pure function of the workspace file tree — no timestamps, no
//! run-dependent content — so a sync with no file changes produces byte-for-byte
//! identical output.
//!
//! Implemented in M2.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use crate::error::AxiomataError;
use crate::memory::walker::{FileEntry, WorkspaceTree};

/// Opening marker of the generated block.
pub const ROUTER_START: &str = "<!-- AXIOMATA-ROUTER:START -->";
/// Closing marker of the generated block.
pub const ROUTER_END: &str = "<!-- AXIOMATA-ROUTER:END -->";

/// Comment line placed just inside the block, so a human opening the file knows
/// not to hand-edit it.
const GENERATED_NOTE: &str = "<!-- Generated by Axiomata-OS. Edit anywhere outside this block; it is overwritten on sync. -->";

/// Renders the root `CLAUDE.md` block: the list of top-level areas plus any
/// loose files sitting directly in the workspace root.
pub fn render_root_block(tree: &WorkspaceTree) -> String {
    let mut body = String::new();
    body.push_str("## Workspace map\n");

    if tree.areas.is_empty() && tree.loose.is_empty() {
        body.push_str("\n_(the workspace is empty)_\n");
        return wrap(&body);
    }

    if !tree.areas.is_empty() {
        body.push_str("\n### Areas\n\n");
        for (area, entries) in &tree.areas {
            let n = entries.len();
            let plural = if n == 1 { "file" } else { "files" };
            let _ = writeln!(
                body,
                "- **{area}/** — {n} {plural} · [index]({area}/CLAUDE.md)"
            );
        }
    }

    if !tree.loose.is_empty() {
        body.push_str("\n### Loose files\n\n");
        for entry in &tree.loose {
            body.push_str(&render_entry_line(&entry.rel_path, entry));
        }
    }

    wrap(&body)
}

/// Renders one area's `CLAUDE.md` block: its files, paths shown relative to the
/// area directory.
pub fn render_area_block(area: &str, entries: &[FileEntry]) -> String {
    let mut body = String::new();
    let _ = writeln!(body, "## {area}/ — index");
    body.push('\n');

    if entries.is_empty() {
        body.push_str("_(no files)_\n");
        return wrap(&body);
    }

    let prefix = format!("{area}/");
    for entry in entries {
        let shown = entry
            .rel_path
            .strip_prefix(&prefix)
            .unwrap_or(&entry.rel_path);
        body.push_str(&render_entry_line(shown, entry));
    }
    wrap(&body)
}

/// `` - `path` `` or `` - `path` — Title ``, newline-terminated.
fn render_entry_line(shown_path: &str, entry: &FileEntry) -> String {
    match &entry.title {
        Some(title) => format!("- `{shown_path}` — {title}\n"),
        None => format!("- `{shown_path}`\n"),
    }
}

/// Wraps a rendered body in the start/end markers and the generated-note line.
fn wrap(body: &str) -> String {
    format!(
        "{ROUTER_START}\n{GENERATED_NOTE}\n\n{}\n{ROUTER_END}",
        body.trim_end()
    )
}

/// Result of writing a router block into a file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockWrite {
    /// The file was created or its block changed and was rewritten.
    Written,
    /// The file already contained exactly this block — nothing was written.
    Unchanged,
}

/// Inserts or replaces the router block in the file at `path`, leaving every
/// other byte of the file untouched.
///
/// - No file yet → the file is created containing just the block.
/// - File without a block → the block is appended (with a blank-line gap).
/// - File with a block → only the region between the markers is replaced.
///
/// The file is only written when the resulting content actually differs, so
/// repeated syncs don't churn mtimes.
///
/// Errors:
///     [`AxiomataError::Io`] on a read or write failure;
///     [`AxiomataError::InvalidRouter`] if the file has a start marker but no
///     end marker (an ambiguous, likely hand-mangled block).
pub fn upsert_block(path: &Path, block: &str) -> Result<BlockWrite, AxiomataError> {
    let existing = match fs::read_to_string(path) {
        Ok(text) => Some(text),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => None,
        Err(source) => {
            return Err(AxiomataError::Io {
                path: path.to_path_buf(),
                source,
            });
        }
    };

    let updated = match &existing {
        None => format!("{block}\n"),
        Some(text) => splice_block(path, text, block)?,
    };

    if existing.as_deref() == Some(updated.as_str()) {
        return Ok(BlockWrite::Unchanged);
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| AxiomataError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    fs::write(path, &updated).map_err(|source| AxiomataError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(BlockWrite::Written)
}

/// Returns `text` with its router block replaced by `block`, or with `block`
/// appended if there is no existing block.
fn splice_block(path: &Path, text: &str, block: &str) -> Result<String, AxiomataError> {
    let Some(start) = text.find(ROUTER_START) else {
        // Append, keeping a single blank line between old content and the block.
        let base = text.trim_end();
        return Ok(if base.is_empty() {
            format!("{block}\n")
        } else {
            format!("{base}\n\n{block}\n")
        });
    };

    let after_start = start + ROUTER_START.len();
    let end_rel =
        text[after_start..]
            .find(ROUTER_END)
            .ok_or_else(|| AxiomataError::InvalidRouter {
                path: path.to_path_buf(),
                reason: "found the AXIOMATA-ROUTER:START marker but no matching END marker"
                    .to_owned(),
            })?;
    let end = after_start + end_rel + ROUTER_END.len();

    Ok(format!("{}{block}{}", &text[..start], &text[end..]))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::unique_temp_dir;

    fn entry(rel: &str, title: Option<&str>) -> FileEntry {
        FileEntry {
            rel_path: rel.to_owned(),
            title: title.map(str::to_owned),
        }
    }

    fn sample_tree() -> WorkspaceTree {
        let mut tree = WorkspaceTree::default();
        tree.loose.push(entry("inbox.md", Some("Quick capture")));
        tree.loose.push(entry("readme.md", None));
        tree.areas.insert(
            "projects".to_owned(),
            vec![
                entry("projects/a.md", Some("Project A")),
                entry("projects/nested/deep.md", None),
            ],
        );
        tree.areas
            .insert("reference".to_owned(), vec![entry("reference/x.md", None)]);
        tree
    }

    #[test]
    fn root_block_lists_areas_and_loose_files_and_is_deterministic() {
        let tree = sample_tree();
        let a = render_root_block(&tree);
        let b = render_root_block(&tree);
        assert_eq!(a, b);

        assert!(a.starts_with(ROUTER_START));
        assert!(a.ends_with(ROUTER_END));
        assert!(a.contains("- **projects/** — 2 files · [index](projects/CLAUDE.md)"));
        assert!(a.contains("- **reference/** — 1 file · [index](reference/CLAUDE.md)"));
        assert!(a.contains("- `inbox.md` — Quick capture"));
        assert!(a.contains("- `readme.md`\n"));
    }

    #[test]
    fn area_block_shows_paths_relative_to_the_area() {
        let block = render_area_block("projects", &sample_tree().areas["projects"]);
        assert!(block.contains("## projects/ — index"));
        assert!(block.contains("- `a.md` — Project A"));
        assert!(block.contains("- `nested/deep.md`\n"));
        assert!(!block.contains("projects/a.md"));
    }

    #[test]
    fn empty_tree_renders_a_placeholder() {
        let block = render_root_block(&WorkspaceTree::default());
        assert!(block.contains("_(the workspace is empty)_"));
    }

    #[test]
    fn upsert_creates_file_with_just_the_block() {
        let dir = unique_temp_dir("axiomata-test-router-create");
        let path = dir.join("CLAUDE.md");
        let block = render_root_block(&sample_tree());

        assert_eq!(upsert_block(&path, &block).unwrap(), BlockWrite::Written);
        let written = fs::read_to_string(&path).unwrap();
        assert_eq!(written, format!("{block}\n"));

        // Second identical upsert writes nothing.
        assert_eq!(upsert_block(&path, &block).unwrap(), BlockWrite::Unchanged);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn upsert_replaces_only_the_block_and_keeps_the_rest() {
        let dir = unique_temp_dir("axiomata-test-router-splice");
        let path = dir.join("CLAUDE.md");
        fs::create_dir_all(&dir).unwrap();
        let old_block = "<!-- AXIOMATA-ROUTER:START -->\nold body\n<!-- AXIOMATA-ROUTER:END -->";
        fs::write(
            &path,
            format!("# My hand-written notes\n\nKeep me.\n\n{old_block}\n\nTrailing prose.\n"),
        )
        .unwrap();

        let new_block = render_area_block("projects", &sample_tree().areas["projects"]);
        assert_eq!(
            upsert_block(&path, &new_block).unwrap(),
            BlockWrite::Written
        );

        let result = fs::read_to_string(&path).unwrap();
        assert!(result.starts_with("# My hand-written notes\n\nKeep me.\n\n"));
        assert!(result.ends_with("\n\nTrailing prose.\n"));
        assert!(result.contains("- `a.md` — Project A"));
        assert!(!result.contains("old body"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn upsert_appends_when_the_file_has_no_block() {
        let dir = unique_temp_dir("axiomata-test-router-append");
        let path = dir.join("CLAUDE.md");
        fs::create_dir_all(&dir).unwrap();
        fs::write(&path, "# Existing\n\nSome text.\n").unwrap();

        let block = render_root_block(&sample_tree());
        assert_eq!(upsert_block(&path, &block).unwrap(), BlockWrite::Written);

        let result = fs::read_to_string(&path).unwrap();
        assert_eq!(result, format!("# Existing\n\nSome text.\n\n{block}\n"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn upsert_rejects_a_start_marker_without_an_end() {
        let dir = unique_temp_dir("axiomata-test-router-mangled");
        let path = dir.join("CLAUDE.md");
        fs::create_dir_all(&dir).unwrap();
        fs::write(&path, "before\n<!-- AXIOMATA-ROUTER:START -->\ndangling\n").unwrap();

        let err = upsert_block(&path, "x").unwrap_err();
        assert!(matches!(err, AxiomataError::InvalidRouter { .. }));

        let _ = fs::remove_dir_all(&dir);
    }
}
