#!/usr/bin/env bash
# Vendors the UI icons (docs/plans/editor-look.md, K6): a chosen subset of Lucide
# (ISC licence), pinned to one release and checked against its registry checksum,
# written as src/ui/icons/lucide.ts — the inner SVG of each icon by name — plus
# the licence beside it. The output is checked in; nothing is fetched at runtime.
#
# To add an icon: put its Lucide name into ICONS below and run the script again.
#
# Usage: scripts/vendor-icons.sh
set -euo pipefail

PACKAGE="lucide-static"
VERSION="1.48.0"
SHASUM="1e624cfe50e0da5f338b9f3610a30a523d047dca"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HERE/src/ui/icons"
WORK="${TMPDIR:-/tmp}/axiomata-icons"

# Sorted; each is a file `icons/<name>.svg` in the package.
ICONS=(
  archive
  archive-restore
  arrow-down-to-line
  arrow-up-from-line
  book-open
  bot
  bug
  calendar
  check
  chevron-down
  chevron-right
  circle-alert
  circle-check
  code
  columns-2
  columns-3
  container
  copy
  database
  ellipsis
  ellipsis-vertical
  external-link
  eye
  eye-off
  file
  file-archive
  file-braces
  file-code
  file-cog
  file-image
  file-plus
  file-text
  files
  folder
  folder-open
  folder-plus
  folder-tree
  git-branch
  git-commit-horizontal
  git-commit-vertical
  git-compare
  git-merge
  grip-vertical
  history
  inbox
  info
  keyboard
  layout-grid
  list
  list-checks
  lock
  map
  maximize-2
  message-square-plus
  minimize-2
  panel-left
  panel-right
  panels-top-left
  pause
  pencil
  play
  plus
  refresh-cw
  rotate-ccw
  rows-2
  save
  search
  settings
  sliders-horizontal
  square
  step-forward
  terminal
  text-search
  trash-2
  undo-2
  user
  workflow
  wrap-text
  x
)

rm -rf "$WORK"
mkdir -p "$WORK" "$OUT"
cd "$WORK"
TARBALL="$(npm pack --silent "$PACKAGE@$VERSION")"
ACTUAL="$(shasum -a 1 "$TARBALL" | cut -d' ' -f1)"
if [ "$ACTUAL" != "$SHASUM" ]; then
  echo "checksum mismatch for $TARBALL: $ACTUAL (expected $SHASUM)" >&2
  exit 1
fi
tar -xzf "$TARBALL"

node - "$WORK/package/icons" "$OUT/lucide.ts" "$VERSION" "${ICONS[@]}" <<'NODE'
const fs = require("fs");
const [dir, out, version, ...names] = process.argv.slice(2);
const lines = [];
for (const name of names) {
  const svg = fs.readFileSync(`${dir}/${name}.svg`, "utf8");
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s*\n\s*/g, "")
    .trim();
  if (!inner || /<script|on\w+=/i.test(inner)) throw new Error(`unexpected content in ${name}`);
  lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`);
}
fs.writeFileSync(
  out,
  [
    `// Generated by scripts/vendor-icons.sh from lucide-static@${version} (ISC, see LICENSE-lucide) — do not edit.`,
    "// Each entry is the inside of a 24×24 Lucide icon, drawn with `stroke: currentColor` by `ui/Icon.svelte`.",
    "",
    "export const LUCIDE = {",
    ...lines,
    "} as const;",
    "",
    "export type IconName = keyof typeof LUCIDE;",
    "",
  ].join("\n"),
);
NODE
cp "$WORK/package/LICENSE" "$OUT/LICENSE-lucide"
echo "wrote ${#ICONS[@]} icons to $OUT/lucide.ts"
