<!--
  A file's or a folder's icon in the tree (`docs/plans/editor-look.md`, LK4,
  K5), in the style chosen in the editor settings. The vendored sets bring
  their own colours (`{@html}` of static, checked-in drawings, vetted when
  generated by `scripts/vendor-file-icons.sh`); monochrome is a Lucide icon in
  the text colour.
-->
<script lang="ts">
  import { fileIconDrawing, fileIconKey, lightTheme } from "../core/fileIcons";
  import Icon from "../ui/Icon.svelte";
  import { editorSettings } from "./editorSettings";

  interface Props {
    name: string;
    /** A folder; `open` when it shows its entries. */
    folder?: boolean;
    open?: boolean;
  }

  let { name, folder = false, open = false }: Props = $props();

  const drawing = $derived(
    fileIconDrawing(
      $editorSettings.fileIcons,
      folder ? (open ? "folder-open" : "folder") : fileIconKey(name),
      $lightTheme,
    ),
  );
</script>

{#if drawing?.kind === "glyph"}
  <svg class="file-icon" viewBox={drawing.viewBox} aria-hidden="true">{@html drawing.body}</svg>
{:else if drawing?.kind === "lucide"}
  <span class="file-icon mono"><Icon name={drawing.name} size="sm" /></span>
{/if}

<style>
  .file-icon {
    flex: none;
    width: var(--ax-icon-md);
    height: var(--ax-icon-md);
    /* Sets drawn in `currentColor` (Octicons) are muted, as GitHub draws them; coloured sets keep theirs. */
    color: var(--ax-text-muted);
  }

  .mono {
    display: inline-flex;
    align-items: center;
    justify-content: center;
  }
</style>
